name: Build exe

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        sudo sh build.sh
        
