name: Build exe

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r install.txt
    - name: Build exe
      run: |
        pyinstaller -r -W PCToolsBot.py
        mv dist/PCToolsBot.exe PCToolsBot.exe
    - name: Upload exe to artifact
      run:
      - uses: actions/upload-artifact@v3
        with:
            name: PCToolsBot.exe
            path: PCToolsBot.exe
